### PR TITLE
fix(database): handle loading circular eager relations

### LINKED ISSUE #1494: Circular eager loads
When two models reference eachother and both eager load the relation, you end up with an infinite loop

### PR DESCRIPTION
**Pull request by WendellAdriel**
## Summary

Modified `ModelInspector` to track visited model types and prevent infinite recursion:

* Tracking visited model types in an array as we traverse the relationship tree
* Before recursing into a relation, check if the target model type is already in the visited path
* If a circular reference is detected, skip that relation to prevent infinite recursion
* Passing the updated visited paths array to recursive calls

Fixes #1494

### CODE REVIEW

**Comment by WendellAdriel** [comment]
Hey @brendt I opened this PR based on an old one I created before.
I'm seeing that it failed one test case.

However, this doesn't seem related to any of the changes I did.
How should I proceed in this case?

File: tests/Integration/Database/CircularEagerLoadingTest.php [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+
+use Tests\Tempest\Fixtures\Models\UserWithEager;
+use Tests\Tempest\Integration\FrameworkIntegrationTestCase;
+
+use function Tempest\Database\inspect;
+
+/**
+ * @internal
+ */
+final class CircularEagerLoadingTest extends FrameworkIntegrationTestCase
```
Comment (brendt) [inline tests/Integration/Database/CircularEagerLoadingTest.php:20]: I think I'd add one more integration test here that actually performs the database query and maps unto the models, I like to have these high-level tests to make sure we didn't miss anything. 

Apart from that, looking good!

Comment (WendellAdriel) [reply tests/Integration/Database/CircularEagerLoadingTest.php:20]: Thanks @brendt 
Should I create a migration for each table then to be able to test the inserts and reads?

Comment (brendt) [reply tests/Integration/Database/CircularEagerLoadingTest.php:20]: Yes :)

**Comment by WendellAdriel** [comment]
Hey @brendt I finished the changes, there's one failing test but IDK if it's realted to my changes tho. Can you help me checking?

**Review by brendt — APPROVED** [review]

**Comment by brendt** [comment]
Nice! Thanks for the contribution: I wasn't looking forward doing this myself because I had already spent so much time in the ORM lately :p So I'm happy you took it on to do :)

**Comment by WendellAdriel** [comment]
@brendt I'm happy to help, I'll take a look at other things to help with!
And I like to work with ORMs, so it was nice to work on this one! :partying_face:
