### PR TITLE
fix(view): comment out empty slots

### LINKED ISSUE #937: Link tags are placed wrong
On http://tempestphp.com.test/ the favicon link tags end up in the body instead of head.

### PR DESCRIPTION
**Pull request by brendt**
Closes #937

### CODE REVIEW

File: src/Tempest/View/src/Elements/ViewComponentElement.php [hunk 1]
```diff
@@ -104,7 +104,9 @@ public function compile(): string
                     $slot = $this->getSlot($name);
 
                     if ($slot === null) {
-                        return $matches[0];
+                        // A slot doesn't have any content, so we'll comment it out.
+                        // This is to prevent DOM parsing errors (slots in <head> tags is one example, see #937)
+                        return '<!--' . $matches[0] . '-->';
```
Comment (innocenzi) [inline src/Tempest/View/src/Elements/ViewComponentElement.php:109]: Maybe comment it only in development, and remove it completely in production? Vue does that

Comment (brendt) [reply src/Tempest/View/src/Elements/ViewComponentElement.php:109]: Agree: https://github.com/tempestphp/tempest-framework/issues/949
