### PR TITLE
fix(database): prevent deeply nested has many map adding extra empty object

### LINKED ISSUE #1994: Deeply nested has-many map creates additional empty relation object
### Tempest version

3.0

### PHP version

8.5

### Operating system

Linux

### Description

When mapping query data with deeply nested HasMany relations, you get an extra empty object in the relation property array:

```php
$data = [
    [
        'authors.id' => 1,
        'books.id' => 1,
        'books.chapters.id' => 1,
        'books.chapters.title' => 'LOTR 1.1',
    ],
    [
        'authors.id' => 1,
        'books.id' => 1,
        'books.chapters.id' => 2,
        'books.chapters.title' => 'LOTR 1.2',
    ],
];

$authors = map($data)->with(SelectModelMapper::class)->to(Author::class);

$this->assertCount(1, $authors[0]->books);

/*
 * 1) Tests\Tempest\Integration\Database\Mappers\SelectModelMapperTest::test_deeply_nested_has_many_map
 * Failed asserting that actual size 2 matches expected size 1.
 */
```

```
var_dump($authors[0]->books);

array(2) {
  [0]=>
  object(Tests\Tempest\Fixtures\Modules\Books\Models\Book)#4401 (4) {
    ["title"]=>
    uninitialized(string)
    ["author"]=>
    object(Tests\Tempest\Fixtures\Modules\Books\Models\Author)#5037 (2) {
      ["name"]=>
      uninitialized(string)
      ["type"]=>
      uninitialized(?Tests\Tempest\Fixtures\Modules\Books\Models\AuthorType)
      ["books"]=>
      *RECURSION*
      ["publisher"]=>
      uninitialized(?Tests\Tempest\Fixtures\Modules\Books\Models\Publisher)
      ["id"]=>
      object(Tempest\Database\PrimaryKey)#3540 (1) {
        ["value"]=>
        int(1)
      }
    }
    ["chapters"]=>
    array(2) {
      [0]=>
      object(Tests\Tempest\Fixtures\Modules\Books\Models\Chapter)#4946 (3) {
        ["title"]=>
        string(8) "LOTR 1.1"
        ["contents"]=>
        uninitialized(?string)
        ["book"]=>
        *RECURSION*
        ["id"]=>
        object(Tempest\Database\PrimaryKey)#4953 (1) {
          ["value"]=>
          int(1)
        }
      }
      [1]=>
      object(Tests\Tempest\Fixtures\Modules\Books\Models\Chapter)#4961 (3) {
        ["title"]=>
        string(8) "LOTR 1.2"
        ["contents"]=>
        uninitialized(?string)
        ["book"]=>
        *RECURSION*
        ["id"]=>
        object(Tempest\Database\PrimaryKey)#4960 (1) {
          ["value"]=>
          int(2)
        }
      }
    }
    ["isbn"]=>
    NULL
    ["id"]=>
    object(Tempest\Database\PrimaryKey)#3502 (1) {
      ["value"]=>
      int(1)
    }
  }
  [1]=>
  object(Tests\Tempest\Fixtures\Modules\Books\Models\Book)#3536 (3) {
    ["title"]=>
    uninitialized(string)
    ["author"]=>
    object(Tests\Tempest\Fixtures\Modules\Books\Models\Author)#5037 (2) {
      ["name"]=>
      uninitialized(string)
      ["type"]=>
      uninitialized(?Tests\Tempest\Fixtures\Modules\Books\Models\AuthorType)
      ["books"]=>
      *RECURSION*
      ["publisher"]=>
      uninitialized(?Tests\Tempest\Fixtures\Modules\Books\Models\Publisher)
      ["id"]=>
      object(Tempest\Database\PrimaryKey)#3540 (1) {
        ["value"]=>
        int(1)
      }
    }
    ["chapters"]=>
    array(0) {
    }
    ["isbn"]=>
    NULL
    ["id"]=>
    uninitialized(Tempest\Database\PrimaryKey)
  }
}
```

### PR DESCRIPTION
**Pull request by nunntom**
closes #1994

- Added failing assertion to existing test showing the bug
- Removed line in `SelectModelMapper` that adds initial empty model. It doesn't seem necessary since the later `$data->set` adds the full nested path anyway. Please correct me if I'm wrong or if I broke anything. Tests are all still passing (including the failing one I added).

### CODE REVIEW

File: packages/database/src/Mappers/SelectModelMapper.php
Comment (nunntom) [inline packages/database/src/Mappers/SelectModelMapper.php:155]: This `$data-set` seems like it adds the whole recursive path to this key, making the earlier `$data->set` with `$originalKey` unnecessary.

File: packages/database/src/Mappers/SelectModelMapper.php [hunk 1]
```diff
@@ -138,10 +138,6 @@ public function normalizeRow(ModelInspector $model, array $row, MutableArray $da
 
                     $originalKey .= $relation->name . '.';
 
-                    if (! $data->hasKey(trim($originalKey, '.'))) {
-                        $data->set(trim($originalKey, '.'), []);
```
Comment (nunntom) [inline packages/database/src/Mappers/SelectModelMapper.php:142]: When about to add `$key`:  `"books.1.chapters.1.id"`, `$originalKey` is `"books.chapters."` so this adds an associative `"chapters" => []` into the books array.

**Comment by brendt** [comment]
Ping me when ready for review :)

**Comment by nunntom** [comment]
Yes please, ready for review @brendt

**Comment by brendt** [comment]
I wonder if we might have missed a test for this piece of code originally, because I'm kind of skeptical about removing it and everything just… continuing to work. Or, it could also be a leftover from an old iteration. I honestly don't remember.

So I'm going to merge this, and we'll see if something goes wrong :)

**Comment by nunntom** [comment]
Yeah, I don't get what that piece of code could have originally been for. My reasoning is doesn't the later $data->set recursively add any needed unset parents when adding a new child?  Which would make it unnecessary to preemptively add the empty parent. 

If it's any comfort I've been running a composer-patch of this change for a few weeks and haven't seen any issues, though I'm probably not covering anywhere near all use-cases. Fingers crossed!

Thanks for merging! :)

**Comment by brendt** [comment]
I had Claude take a look at it for 10 minutes because I genuinely didn't know anymore. 

I now think it was added to deal with setting an empty array for the first iteration so that the array itself was present. However, we're now using `$data->set($key, $value);` which also does these "initialize missing nested array checks" for us, so the buggy part wasn't needed anymore.

At least, that's my understanding for now. We'll see how it goes :)
