### PR TITLE
fix(database): support pagination with joins and relations

### LINKED ISSUE #1799: `IsDatabaseModel::with` is broken when combined with `paginate`
`self::select()->with('sources')->paginate()`

doesn't add the necessary joins. Broken since 2.10, I believe with this PR: https://github.com/tempestphp/tempest-framework/pull/1725/files

### PR DESCRIPTION
**Pull request by innocenzi**
Closes https://github.com/tempestphp/tempest-framework/issues/1799

### CODE REVIEW

File: packages/database/src/Builder/QueryBuilders/CountQueryBuilder.php [hunk 1]
```diff
@@ -122,6 +137,18 @@ public function toRawSql(): ImmutableString
 
     public function build(mixed ...$bindings): Query
     {
-        return new Query($this->count, [...$this->bindings, ...$bindings])->onDatabase($this->onDatabase);
+        $count = $this->count;
+
+        if ($this->joins !== []) {
```
Comment (brendt) [inline packages/database/src/Builder/QueryBuilders/CountQueryBuilder.php:140]: Why don't we add the joins to the existing statement?

**Review by brendt — DISMISSED** [review]
